### ISSUE TITLE
difference between visual geometry and collision geometry in the simulation

### ISSUE THREAD

**Issue by jxtxwsbn** [ethz-asl/vgn#13]
Hi, 

I noticed that there is a difference between visual geometry and collision geometry.  The gripper can grasp the object even there is a gap between the finger and the object. What's the reason for this phenomenon? Thanks

**Comment by mbreyer** [comment]
This is a behavior of the physics engine. PyBullet recommends that you generate a convex decomposition of the visual geometry using [v-hacd](https://github.com/kmammou/v-hacd) since computing collisions between convex objects is a lot more efficient. It can lead to some artifacts though when the convex approximation does not exactly match the visual mesh.
