### ISSUE TITLE
Gazebo kinect camera : TSDF not generating (tsdf_vol has all zero values)

### ISSUE THREAD

**Issue by aniketghodake10** [ethz-asl/vgn#16]
VGN works well on real kinect camera, but when i use gazebo kinect camera......tsdf_vol has all the values as zero, as a result grasps are not generated

![Screenshot from 2022-03-23 21-17-51](https://user-images.githubusercontent.com/38704659/159740249-a4350e19-fb85-4f5f-9aea-93ec2a8baabf.png)
![Screenshot from 2022-03-23 21-18-37](https://user-images.githubusercontent.com/38704659/159740303-7aa42b8c-134a-4f53-b662-84fb34952b63.png)
d

**Comment by mbreyer** [comment]
It might be due to different image formats. The RealSense node publishes depth images in mm, whereas the Gazebo plugin probably uses meters. Does removing the scaling factor at the end of the following line solve the problem?

https://github.com/ethz-asl/vgn/blob/fdd46109ce38a526ed7e2d52336e07e7f0204f17/scripts/panda_grasp.py#L232

**Comment by aniketghodake10** [comment]
yes, its working now. Thank you. Great work.
