### ISSUE TITLE
Negative voxel index triggered error when training

### ISSUE THREAD

**Issue by Steve-Tod** [ethz-asl/vgn#2]
Hi, I constructed the dataset using the following commands:
`mpirun -np 16 python scripts/generate_data.py --scene pile data/data_blocks_raw`
`python scripts/construct_dataset.py data/data_blocks_raw data/data_blocks`

Then I train the network with: `python scripts/train_vgn.py --dataset data/data_blocks`. After one step, I got an error:
![image](https://user-images.githubusercontent.com/26958167/99546288-3f40ca80-29f1-11eb-9718-940a215579e6.png)

I use `pdb` to debug and found that the error is caused by the negative `index` in the `select` function. The `index` here is the voxel coordinates.

Then I iterate through the data with the scripts in data.ipynb. And I found a few data points have negative coordinates after the round operation (-1 and -2).

Apart from ignoring these data, how can I modify the code to avoid this happening during the dataset generation?

**Comment by mbreyer** [comment]
I wrote a [Jupyter notebook](https://github.com/ethz-asl/vgn/blob/666ae505da63f3351cd7dd63b9de44d631aee543/notebooks/data.ipynb) to balance and clean the data, which gets rid of this problem. Otherwise, one could of course already skip those points inside the [data collection script](https://github.com/ethz-asl/vgn/blob/666ae505da63f3351cd7dd63b9de44d631aee543/scripts/generate_data.py#L104).

**Comment by Steve-Tod** [comment]
Got it, thanks!
