### ISSUE TITLE
ROS and ubuntu version

### ISSUE THREAD

**Issue by RobotBT** [ethz-asl/vgn#8]
Hi, thank you for sharing your code. However, I am a little confused about the version of ROS and ubuntu.  According to the readme, it seems that you used ubuntu 20.04 and ROS Noetic. However, for Franka Robot Arm, the robot seems only support up to ROS Melodic which uses ubuntu 18.04 and python2.  Would you please tell me how did you solve this problem, thank you!

**Comment by mbreyer** [comment]
Hi, yes that was a problem I encountered as well. Originally, I developed the package for ROS melodic, however I decided to upgrade to ROS noetic since newer versions of torch, ignite, scipy, and open3d are not available for python2 anymore. I updated the README with a workaround that allowed me to still run experiments with the Franka arm. This is not ideal, however I expect Franka to release an update for ROS noetic in the near future : )
